version: '3.7'

networks:
  desafio-network:
    driver: bridge

services:
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile 
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
    tty: true
    depends_on:
      - node
    networks:
      - desafio-network

  node:
    build:
      context: ./node
      dockerfile: Dockerfile 
    container_name: node
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - mysql
    networks:
      - desafio-network

  mysql:
    context: ./mysql
    dockerfile: Dockerfile
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafiofullcycle
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - desafio-network
